export const CELL_SIZE = 60;
export const DEFAULT_SUDOKU_BOARD_CELL = 9;
export const LINE_WIDTH = 1;
export const DEFAULT_SUDOKU_BOARD_SIZE = CELL_SIZE * DEFAULT_SUDOKU_BOARD_CELL + (DEFAULT_SUDOKU_BOARD_CELL + 2) * LINE_WIDTH;
export const DEFAULT_KNIGHT_TOUR_CELL = 8;
export const DEFAULT_KNIGHT_TOUR_SIZE = CELL_SIZE * DEFAULT_KNIGHT_TOUR_CELL + (DEFAULT_KNIGHT_TOUR_CELL + 2) * LINE_WIDTH;